
server:

spring:
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /template/
      suffix: .html

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?charsetEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        user-new-id-generator-mapping: false
      show-sql: true
      properties:
        hibernate:
          format_sql: true

  thymeleaf:
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html;charset=UTF-8

  jackson:
    serialization:
      fail-on-empty-beans: false

  http:
    encoding:
      charset: UTF-8